### ISSUE TITLE
Errors when using 44100Hz .wav files

### ISSUE THREAD

**Issue by priyanthini** [festvox/festvox#23]
I completed festival part successfully with 16kHz .wav files. But when I'm trying to use 44100Hz .wav files I'm getting errors. CAtually building prompts was okay. But the problem started in the labeling part. Only .sl files are created. .lab and .slehmm files are not created and it shows errors and labeling part stopped at the middle. 
I need to know do we need to change or edit some files (codes) when we are using a sample rate other than 16kHz.
Please someone help me to overcome this issue.

Thanks in advance.

**Comment by saikrishnarallabandi** [comment]
Hi,

unfortunately the alignment module (labeling) currently only works with 16khz files. To build the voice, this should still be fine though since rest of the code words with any sampling rate. So, an easy alternative is to label using 16khz files and then continue with 44.1Khz. You can do this by the following

cp -r wav wav_44.1khz
./bin/get_wavs wav_44.1khz/* 
./bin/do_build label
cp -r wav_44.1khz/* wav

Let me know if there is any issue

**Comment by priyanthini** [comment]
@saikrishnarallabandi Hi. This also didn't work for me. What can I do now ?

**Comment by saikrishnarallabandi** [comment]
weird. can you paste the output of this command

fname=`ls wav | head -1`
soxi wav/$fname.wav

**Comment by priyanthini** [comment]
I will check and let you know. Thank you.

**Comment by saikrishnarallabandi** [comment]
closing this
